#! /bin/bash

dist=unknown

if [[ "$(command -v pacman)" != "" ]]; then 
	dist="archlinux";
elif [[ "$(command -v apt-get)" != "" ]]; then
	dist="debian";
else 
	echo "Not supported linux distribution" 1>&2;  
	exit 1;
fi



########

# archlinux

if [[ "$dist" == "archlinux" ]]; then

	
	if ! makepkg $@ ; then
		echo "makepkg failed" 1>&2;
		exit 1;
	fi
	


			
########


# debian 

elif [[ "$dist" == "debian" ]]; then

while [ "$1" ] ; do
    arg="$1"
    case $arg in 
	--config) config="$2"; 	shift ;;
	*=*) export ${arg%%=*}="${arg##*=}" ;;
	*) ;;
    esac
    shift; 
done


. $config || exit 1
. PKGBUILD || exit 1


case ${CARCH} in
    x86_64) debarch=amd64 ;;
    *) debarch=${CARCH} ;;
esac

debver="${pkgver/_/~}-${pkgrel}"
debpkg="${pkgname}-${debver}_${debarch}"
pkgdir="$(pwd)/${debpkg}"

control="\
Package: ${pkgname}
Version: ${debver}
Section: cuttle
Priority: optional
Architecture: ${debarch}
Maintainer: A. Myznikov <andrey.myznikov@gmail.com>
Description: ${pkgdesc}
"

rm -rf ${pkgdir} && mkdir -p ${pkgdir}/DEBIAN && cd ${pkgdir} && package && cd ${pkgdir} || exit 1

# control
echo "${control}" > DEBIAN/control


# dirs, links and md5sums
for f in */ ; do 
    if [[ "$f" != "DEBIAN/" ]] ; then 
	find $f -type d -exec echo {} \; >> DEBIAN/dirs
	find $f -type l -exec echo {} \; >> DEBIAN/links
	md5deep -l -r $f >> DEBIAN/md5sums
    fi
done

# conffiles
for d in etc usr/local/etc; do
    if [[ -d $d ]] ; then 
	find $d/ -type f -exec echo {} \; >> DEBIAN/conffiles
    fi
done


echo "Building debian package ${debpkg} " 1>&2
cd ${pkgdir}/.. && dpkg-deb --build ${debpkg} || exit 1


		
########

else 
	
	echo "Not supported linux distribution" 1>&2;  
	exit 1;
	
fi

########
